#!/usr/bin/env python
# -*- coding: utf-8 -*-

# histstat - history for netstat
# https://github.com/vesche/histstat
$ git clone --mirror https://github.com/GistIcon/histstat.git
# Make a bare mirrored clone of the repository

$ cd repository-to-mirror.git
$ git remote set-url --push origin https://github.com/GistIcon/mirrored
# Set the push location to your mirror
